# Generated by Django 5.0 on 2025-12-31 15:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(db_index=True, max_length=500, verbose_name='Nome da Nota')),
                ('note_year', models.PositiveIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano')),
                ('source_path', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Caminho Original')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/%Y/', verbose_name='Arquivo PDF')),
                ('source_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Hash SHA-256')),
                ('original_text', models.TextField(verbose_name='Texto Original')),
                ('sanitized_text', models.TextField(verbose_name='Texto Anonimizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_notes', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
            ],
            options={
                'verbose_name': 'Nota Técnica',
                'verbose_name_plural': 'Notas Técnicas',
                'db_table': 'notes',
                'ordering': ['-note_year', 'note_name'],
                'indexes': [models.Index(fields=['note_year', 'note_name'], name='notes_note_ye_9e807b_idx'), models.Index(fields=['-created_at'], name='notes_created_f9cdd1_idx'), models.Index(fields=['source_hash'], name='notes_source__476e56_idx')],
            },
        ),
    ]
