# Generated by Django 5.0 on 2025-12-31 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('nome', 'Nome'), ('cpf', 'CPF'), ('endereco', 'Endereço'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('rg', 'RG'), ('cnpj', 'CNPJ'), ('outro', 'Outro')], db_index=True, default='outro', max_length=50, verbose_name='Categoria')),
                ('term', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Termo')),
                ('norm_term', models.CharField(db_index=True, editable=False, max_length=255, verbose_name='Termo Normalizado')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Termo',
                'verbose_name_plural': 'Termos',
                'db_table': 'terms',
                'ordering': ['category', 'term'],
                'indexes': [models.Index(fields=['category', 'enabled'], name='terms_categor_5f9fbd_idx'), models.Index(fields=['norm_term'], name='terms_norm_te_9e0c2d_idx')],
                'unique_together': {('category', 'norm_term')},
            },
        ),
    ]
