# Generated by Django 6.0 on 2026-01-01 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('help', 'Ajuda'), ('manual', 'Manual')], max_length=50, unique=True, verbose_name='Página')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(help_text='Conteúdo em HTML. Use tags como <h2>, <p>, <ul>, <li>, etc.', verbose_name='Conteúdo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pages', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Conteúdo de Página',
                'verbose_name_plural': 'Conteúdos de Páginas',
                'db_table': 'page_contents',
                'ordering': ['page_key'],
            },
        ),
    ]
