# Generated by Django 6.0 on 2026-01-01 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('help', 'Ajuda'), ('manual', 'Manual')], db_index=True, max_length=50, verbose_name='Página')),
                ('card_type', models.CharField(choices=[('faq', 'Pergunta Frequente'), ('guide', 'Guia'), ('chapter', 'Capítulo do Manual'), ('info', 'Informação')], max_length=50, verbose_name='Tipo de Card')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('content', models.TextField(help_text='Conteúdo em HTML ou texto simples', verbose_name='Conteúdo')),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição (menor aparece primeiro)', verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cards', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Card de Conteúdo',
                'verbose_name_plural': 'Cards de Conteúdo',
                'db_table': 'content_cards',
                'ordering': ['page', 'order', 'created_at'],
                'indexes': [models.Index(fields=['page', 'is_active', 'order'], name='content_car_page_063c54_idx')],
            },
        ),
    ]
