# Generated by Django 6.0 on 2026-01-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contentcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcard',
            name='link',
            field=models.URLField(blank=True, help_text='URL opcional para link externo ou recurso', max_length=500, null=True, verbose_name='Link'),
        ),
    ]
